[tool.black]
line-length = 127
target-version = ["py37", "py38", "py39", "py310", "py311"]
exclude = '''
/(
    \.git
  | __pycache__
  | \.ipynb_checkpoints
  | venv
  | env
  | \.venv
  | build
  | dist
)/
'''
